name: ManCo
version: 0.2
description: ManCo item spawner
author: xize
authors: [] 
website:

main: tv.mineinthebox.ManCo.manCo
database: false
depend: []
softdepend: [WorldGuard]

commands:
  manco:
    description: main command
    aliases: [mc]
    permission:
    permission-message:

permissions: