name: ManCo
version: {project.version}
description: ManCo item spawner
author: xize
authors: [] 
website:

main: tv.mineinthebox.ManCo.ManCo
database: false
depend: []
softdepend: [WorldGuard, iConomy, Vault, CoreProtect, LogBlock, Prism]

commands:
  manco:
    description: main command
    aliases: [mc]
    permission:
    permission-message:

permissions: